### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by lbarwick** [triforcely/Octave.NET#1]
Hi, I am having issue installing from NuGet:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Octave.NET 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by triforcely** [comment]
Hi @lbarwick , thanks for reaching out.

I created empty ConsoleApp that targets 4.6.1 trying to reproduce your problem but everything works, this was my output when installing package:
`Attempting to gather dependency information for package 'Octave.NET.1.1.0' with respect to project 'ConsoleApp1', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 10,68 ms
Attempting to resolve dependencies for package 'Octave.NET.1.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Octave.NET.1.1.0'
Resolved actions to install package 'Octave.NET.1.1.0'
Retrieving package 'Octave.NET 1.1.0' from 'nuget.org'.
Adding package 'Octave.NET.1.1.0' to folder 'C:\Users\triforcely\source\repos\ConsoleApp1\packages'
Added package 'Octave.NET.1.1.0' to folder 'C:\Users\triforcely\source\repos\ConsoleApp1\packages'
Added package 'Octave.NET.1.1.0' to 'packages.config'
Successfully installed 'Octave.NET 1.1.0' to ConsoleApp1
Executing nuget actions took 597,1 ms
Time Elapsed: 00:00:00.6450377
========== Finished ==========
`
I'm using latest VS2017 Community (v. 15.8.8) with NuGet Package Manager 4.6.0.

What version of IDE are you using? Can you provide sample solution files where this problem can be reproduced?

**Comment by triforcely** [comment]
In the meantime you can try this prerelease package https://www.nuget.org/packages/Octave.NET/2.0.0-prerelease1

**Comment by lbarwick** [comment]
Thanks Michal,

Got a bit further:

[cid:09ffc867-6bc6-456b-b933-4155c8225819]
________________________________

**Comment by triforcely** [comment]
@lbarwick did new package work? Can this issue be closed?

**Comment by lbarwick** [comment]
Hi, yes it did work. Thank you.

I had to put octaveCliExe in Windows’ path as you mentioned. It might be useful to describe how to do that in your ReadMe (for us non teckie types)!

Also, please note that you need to restart VS for it to come into effect - took a while to figure that out!

Working very well now - thanks again.

Sent from my iPhone

On 29 Oct 2018, at 10:35, Michał Wilski <notifications@github.com<mailto:notifications@github.com>> wrote:


@lbarwick<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flbarwick&data=02%7C01%7C%7C838bcb176b4d42b0430e08d63d8a2ce8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636764060992046106&sdata=%2FTWTS44UF7Oy0jtiBkRov%2FFKGxjKQ1k0Un%2B8%2BYfYm%2Fk%3D&reserved=0> did new package work? Can this issue be closed?
