### ISSUE TITLE
OctaveScriptError: error: sq_string cannot be indexed with

### ISSUE THREAD

**Issue by legenself** [triforcely/Octave.NET#10]
Hello I want Use it in My WebSite
so i print it to file
but it says 'OctaveScriptError: error: sq_string cannot be indexed with'
this is my code
```
var script = @"
x = -10:0.1:10;
y = sin (x);
handle = plot (x, y);
print('"+ uid + "'.png','-dpng') ";
 var a=   octave.Execute(script, int.MaxValue);
```

**Comment by triforcely** [comment]
Dump the resulting string, try to run in Octave, notice that it doesn't run there.

This IS NOT Octave support. Always try your scripts first in plain Octave.

**Comment by triforcely** [comment]
```
x = -10:0.1:10;
y = sin (x);
handle = plot (x, y);
print('32248de4-cd86-4a93-894e-1609652c5617'.png','-dpng')
```

It seems that generated file name is wrong, too many " ' ".

**Comment by legenself** [comment]
thank you........Its my fault....
