### ISSUE TITLE
I want to run Octave plot script in my website,Is there better solution for it ?

### ISSUE THREAD

**Issue by legenself** [triforcely/Octave.NET#11]
my solution:
1. print result to image file
2. give the file url to website

but its not efficient, lose interaction  , and it will open new window for plot (so i must close it  manually or by code 'close'),  

so i want to ask Is there better solution for it ?
how does the [website]( http://octave-online.net) accomplish it
thank you~~~~

**Comment by triforcely** [comment]
You need to figure out how to do this in Octave. I'm not going to help you further because it is unrelated to the project, sorry.

**Comment by legenself** [comment]
thank you
