### ISSUE TITLE
What about 6.x compatibility ?

### ISSUE THREAD

**Issue by cgrard** [triforcely/Octave.NET#13]
Hi there,

I was wondering what would be the compatibility with the latest Octave 6.x releases (6.2.0 at the time of writing)?
Are breaking changes usually expected with major releases (in essence what happened to make it compatible with 5.x two years ago)?

Regards

**Comment by triforcely** [comment]
Hello @cgrard ,

It should work since it interfaces with Octave CLI. Octave 5.x is mentioned as compatible because I worked with this version back then.
