### ISSUE TITLE
The graphical interface cannot be displayed

### ISSUE THREAD

**Issue by fangwancong** [triforcely/Octave.NET#15]
I run the following commands on Octave-GUI, everything works fine and shows a 3D pattern interface. If I execute with Octave.NET, there is no graphical interface displayed.

[x, y, z] = sphere (40);
surf (3*x, 3*y, 3*z);
axis equal;
title ("sphere of radius 3");

**Comment by triforcely** [comment]
You need to hold the execution until the plot is closed

https://github.com/triforcely/Octave.NET/blob/master/examples/Octave.NET.Examples.DisplayPlot/Program.cs

**Comment by fangwancong** [comment]
> You need to hold the execution until the plot is closed
> 
> https://github.com/triforcely/Octave.NET/blob/master/examples/Octave.NET.Examples.DisplayPlot/Program.cs

Unfortunately, I ran the example above but it still doesn't work, I copy the above script to octave-cli to run it works, I don't know why it does, I'm using version 6.2.0 and windows platform.

**Comment by fangwancong** [comment]
Some updates when I uninstall 6.2.0 and then install 5.2.0, it works and I think it's because it's not compatible with 6.2.0.

**Comment by triforcely** [comment]
There is nothing that can be incompatible. After all, Octave.NET just proxies your commands to octave-cli.
