### ISSUE TITLE
Does it support Octave 4.4.1 on Windows 7/10?

### ISSUE THREAD

**Issue by 3r1k0n** [triforcely/Octave.NET#4]
I am having trouble running the example project.
I have Octave 4.4.1 installed as I can't find the links for 4.4.0 and have added "C:\Octave\Octave-4.4.1\bin" to the System Path variable.
The path never gets loaded in the octave object and it's causing to throw an exception.
If I manually specify the path to the bin, the result is the same.

![image](https://user-images.githubusercontent.com/10796765/49268895-2c154880-f430-11e8-947e-caac757f3ab2.png)

**Comment by 3r1k0n** [comment]
.."Also, please note that you need to restart VS for it to come into effect - took a while to figure that out! Working very well now - thanks again."

I will try this tomorrow

**Comment by triforcely** [comment]
![image](https://user-images.githubusercontent.com/12202969/49273392-0a8a8000-f475-11e8-9445-71afff42c2aa.png)

So you need to use "C:\Octave\Octave-4.4.1\bin\octave-cli.exe" if you want to specify it in your code.

However, if you want it to be available system-wide, you need to add something like this to system PATH and remove line 10 from your code:
![image](https://user-images.githubusercontent.com/12202969/49273486-65bc7280-f475-11e8-8b87-9c76422b638d.png)

**Comment by 3r1k0n** [comment]
I did both and more. The result was always the same.

**Comment by triforcely** [comment]
So octave-cli.exe does not exist on your hard drive. If it doesn't work in command line, it won't work in this library.

**Comment by 3r1k0n** [comment]
Octave gui and octave-cli.exe are both installed and work otherwise.

I will try to restart VS and/or the machine and get back with the results

**Comment by 3r1k0n** [comment]
Just to confirm, it works after restarting Visual Studio.

Although it might have to do with Path's visibility after being updated, I don't know why setting the path directly wouldn't work. (I tried setting it directly to the exe)

**Comment by CptWesley** [comment]
> (I tried setting it directly to the exe)

This does not work on Windows in general, not an Octave specific issue.
