### ISSUE TITLE
Library fails with "error: : all arguments must be strings" error message.

### ISSUE THREAD

**Issue by bemoregt** [triforcely/Octave.NET#7]
Hi, @CptWesley @triforcely 

I met this error when run this code:

 using (var octave = new OctaveContext())
            {
                // Note: your octave-cli must support some plot backend, in case of problems investigate manually in octave-cli

                var script = @"
x = -10:0.1:10;
y = sin (x);
filename= 'aa.txt';
save(filename, y);
handle = plot (x, y);

title (""Hello from C#"");
xlabel (""x"");
ylabel (""sin (x)"");

waitfor(handle); #                 <- without that plot window would not show 
                ";
                octave.Execute(script);
            }
---------------------------------------
Error: "error: : all arguments must be strings\n"

What's wrong to me?

Thanks.

from @bemoregt.

**Comment by bemoregt** [comment]
Hi, @CptWesley @triforcely 

??

**Comment by triforcely** [comment]
Hi @bemoregt,

Can you run tests from Octave.NET.Tests project and send us the results?

Also, tell me more about your environment (.NET version, Octave version and OS language).

**Comment by bemoregt** [comment]
Hi, @triforcely @CptWesley 

Basic test project is well runs. There is no errors.

and My Environment is:
MacOSX Mojave, Xamarin Workbooks, Octave.net, Octave for mac 4.4.1.

But Mono & .Net Core is well runs..

Thanks.

**Comment by triforcely** [comment]
Looks like your environment is incorrectly configured or the library does not support MacOSX. I'm closing the issue since I can't troubleshoot that.
