### ISSUE TITLE
I've successfully tested below code in OSX.

### ISSUE THREAD

**Issue by bemoregt** [triforcely/Octave.NET#8]
Hi, @CptWesley @triforcely 

I've successfully tested below code in OSX.
Compiled in VS for mac.
--------------------------------------------
using System;
using System.IO;
using Octave.NET;

namespace ConsoleOctave1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var octave = new OctaveContext())
            {
                octave.Execute("pkg load image;");
                double[][] result = octave
                    .Execute("aa=peaks(256)")
                    .AsMatrix();// 10

                Console.WriteLine(result[1][1].ToString());

                StreamWriter sw1;
                sw1 = new StreamWriter("data.txt");
                for (int i = 0; i < 256; i++)
                {
                    for (int j = 0; j < 256; j++)
                    {
                        sw1.WriteLine(result[i][j].ToString());
                    }
                }
                sw1.Dispose();

            }//using Octave
        }// method
    }// class
}// namespace
--------------------------------------

And Now, I want saving image from octave.
How can I save my octave image using Octave.net?

**Comment by triforcely** [comment]
Use octave functions for that. This project is an Octave wrapper and I'm not going to provide support related to the actual Octave functionality.
