### ISSUE TITLE
I have met this error when run. 

### ISSUE THREAD

**Issue by bemoregt** [triforcely/Octave.NET#9]
Hi, @CptWesley @triforcely 

I have met this error when run. 
"error: : all arguments must be strings\n"

What's wrong to me?

using System;
using System.IO;
using Octave.NET;

namespace ConsoleOctave1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var octave = new OctaveContext())
            {
                octave.Execute("pkg load image;");
                double[][] result = octave
                    .Execute("aa=peaks(256)")
                    .AsMatrix();// 10

                double[][] bb = octave
                    .Execute("bb=aa.+1")
                    .AsMatrix();// 10

                var cc = octave
                    .Execute("f1='aa.mat'")
                    .AsSpan();
                        
                var dd = octave
                    .Execute("save(f1, bb);")    <------ Error occurs at here. ###########
                    .AsMemory();// 10

                Console.WriteLine(bb[1][1].ToString());

                StreamWriter sw1;
                sw1 = new StreamWriter("data.txt");
                for (int i = 0; i < 256; i++)
                {
                    for (int j = 0; j < 256; j++)
                    {
                        sw1.WriteLine(bb[i][j].ToString());
                    }
                }
                sw1.Dispose();

            }//using Octave
        }// method
    }// class
}// namespace_

Thanks in advance.

**Comment by triforcely** [comment]
I'm not going to debug your octave scripts.
